### ISSUE TITLE
npn angular install issue

### ISSUE THREAD

**Issue by kumarganesh2814** [beeman/tutorial-angular-styling-clarity#2]

**Comment by kumarganesh2814** [comment]
Hi 
I see below errors while trying first step
```npm install -g @angular/cli@latest
(node:54419) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:54419) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:54419) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:54419) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:54419) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:54419) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:54419) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:54419) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:54419) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:54419) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
/root/.nvm/versions/node/v12.9.0/bin/ng -> /root/.nvm/versions/node/v12.9.0/lib/node_modules/@angular/cli/bin/ng

> @angular/cli@8.3.0 postinstall /root/.nvm/versions/node/v12.9.0/lib/node_modules/@angular/cli
> node ./bin/postinstall/script.js

internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v12.9.0/lib/node_modules/@angular/cli/bin/postinstall/script.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @angular/cli@8.3.0 postinstall: `node ./bin/postinstall/script.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @angular/cli@8.3.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Any Suggestion please

Best Regards
Ganesh Kumar

**Comment by Enriquecerviro** [comment]
get out from that route and do it con desktop; 
>user/desktop: mkdir newFolder
> cd newFolder
>user/desktop/newFolder: ng new appName
